name: Watch Your Profamity
description: Remove profanity from your project
author: jslattery26
branding:
  icon: life-buoy
  color: purple
inputs:
  replace:
    description: The new string to be replaced
    required: false
  include:
    description: A glob of files to include in our find and replace
    required: false
    default: '**' # Include everything by default
  exclude:
    description: A glob of files to exclude in our find and replace
    default: '.git/**' # Ignore the `.git` directory by default
    required: false
outputs:
  modifiedFiles:
    description: The number of files which have been modified
runs:
  using: node16
  main: 'dist/index.js'
