name: 'Watch Your Profamity'
description: 'Removes all profanity from your project'
author: 'Jack Slattery'
branding:
  color: purple
  icon: life-buoy
inputs:
  source:
    description: 'The text you want to run this action on'
    required: true
  find:
    description: 'The text you are looking for'
    required: true
  replace:
    description: 'The text you want to replace with'
    required: true
  replaceAll:
    description: 'Replace all occurrences?'
    required: false
outputs:
  value:
    description: 'The new value after find-and-replace has been run'
runs:
  using: 'node16'
  main: 'index.js'
