on: [push]

jobs:
  watch-your-profamity-job:
    runs-on: ubuntu-latest
    name: 'Get rid of all that profanity!'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run find-and-replace to remove refs/heads/
        uses: jslattery26/watch_your_profamity@3
        id: watchyourprofamity
        with:
          source: ${{ github.ref }}
          find: 'refs/heads/'
          replace: ''
      - name: Get the above output
        run: echo "The replaced value is ${{ steps.watchyourprofamity.outputs.value }}"
      - name: Run find-and-replace to remove slashes
        uses: jslattery26/watch_your_profamity@1
        id: watchyourprofamity2
        with:
          source: ${{ steps.watchyourprofamity.outputs.value }}
          find: '/'
          replace: '-'
      - name: Get the final output
        run: echo "The replaced value is ${{ steps.watchyourprofamity2.outputs.value }}"
