on: [push]

jobs:
  watch-your-profamity-job:
    runs-on: ubuntu-latest
    name: 'Get rid of all that profanity!'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run find-and-replace to remove refs/heads/
        uses: jslattery26/watch_your_profamity@0.0.4
        id: watchyourprofamity
        with:
          source: ${{ github.ref }}
          find: 'refs/heads/'
          replace: ''
      - name: Get the above output
        run: echo "The replaced value is ${{ steps.watchyourprofamity.outputs.value }}"
