name: Release

on:
  pull_request:
  push:
    paths:
      - 'package.json'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checking out
        uses: actions/checkout@v3

      - name: String Replacer
        uses: jslattery26/watch_your_profamity@0.0.5
        with:
          include: |
            **/README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
