name: Remove Profanity
'on':
  push:
    branches:
      - main

jobs:
  remove-profanity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checking out
        uses: actions/checkout@v4

      - name: String Replacer
        uses: jslattery26/watch_your_profamity@main
        with:
          include: |
            **/README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Removing that profanity dawg
          branch: ${{ github.ref }}
